<?xml version="1.0"?>
<package format="2">
  <name>tocabi_cc</name>
  <version>1.0.0</version>
  <description>The tocabi_cc package</description>

  <maintainer email="jasonshin0537@snu.ac.kr">Jaeyong Shin</maintainer>
  <author email="jasonshin0537@snu.ac.kr">Jaeyong Shin</author>

  <license>TODO</license>



  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <build_depend>tocabi_lib</build_depend>
  <build_export_depend>tocabi_lib</build_export_depend>
  <exec_depend>tocabi_lib</exec_depend>
  <build_depend>tocabi_msgs</build_depend>
  <build_export_depend>tocabi_msgs</build_export_depend>
  <exec_depend>tocabi_msgs</exec_depend>
  <build_depend>yaml-cpp</build_depend>
  <exec_depend>yaml-cpp</exec_depend>

  <export>
  </export>
</package>
