is_on_robot: false
write_file: true
weight: "policy3d-lcp10DR-pctrl.onnx"
cmd: "global_command.csv"
cmd_mode: 1 # 0: local, 1: global
policy_mode: 1 # 0: torque control, 1: position control
hz: 50 # Hz
preview_height: 0.728